/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as PartyRouteImport } from './routes/party'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as NpcsRouteImport } from './routes/npcs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChronicleCampaignIdRouteImport } from './routes/chronicle.$campaignId'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsRoute = NpcsRouteImport.update({
  id: '/npcs',
  path: '/npcs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleCampaignIdRoute = ChronicleCampaignIdRouteImport.update({
  id: '/chronicle/$campaignId',
  path: '/chronicle/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/docs': typeof DocsRoute
  '/items': typeof ItemsRoute
  '/login': typeof LoginRoute
  '/npcs': typeof NpcsRoute
  '/oracle': typeof OracleRoute
  '/party': typeof PartyRoute
  '/quests': typeof QuestsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/chronicle/$campaignId': typeof ChronicleCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/docs': typeof DocsRoute
  '/items': typeof ItemsRoute
  '/login': typeof LoginRoute
  '/npcs': typeof NpcsRoute
  '/oracle': typeof OracleRoute
  '/party': typeof PartyRoute
  '/quests': typeof QuestsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/chronicle/$campaignId': typeof ChronicleCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/docs': typeof DocsRoute
  '/items': typeof ItemsRoute
  '/login': typeof LoginRoute
  '/npcs': typeof NpcsRoute
  '/oracle': typeof OracleRoute
  '/party': typeof PartyRoute
  '/quests': typeof QuestsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/chronicle/$campaignId': typeof ChronicleCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/docs'
    | '/items'
    | '/login'
    | '/npcs'
    | '/oracle'
    | '/party'
    | '/quests'
    | '/sessions'
    | '/settings'
    | '/usage'
    | '/chronicle/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/docs'
    | '/items'
    | '/login'
    | '/npcs'
    | '/oracle'
    | '/party'
    | '/quests'
    | '/sessions'
    | '/settings'
    | '/usage'
    | '/chronicle/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/docs'
    | '/items'
    | '/login'
    | '/npcs'
    | '/oracle'
    | '/party'
    | '/quests'
    | '/sessions'
    | '/settings'
    | '/usage'
    | '/chronicle/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DocsRoute: typeof DocsRoute
  ItemsRoute: typeof ItemsRoute
  LoginRoute: typeof LoginRoute
  NpcsRoute: typeof NpcsRoute
  OracleRoute: typeof OracleRoute
  PartyRoute: typeof PartyRoute
  QuestsRoute: typeof QuestsRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  UsageRoute: typeof UsageRoute
  ChronicleCampaignIdRoute: typeof ChronicleCampaignIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs': {
      id: '/npcs'
      path: '/npcs'
      fullPath: '/npcs'
      preLoaderRoute: typeof NpcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle/$campaignId': {
      id: '/chronicle/$campaignId'
      path: '/chronicle/$campaignId'
      fullPath: '/chronicle/$campaignId'
      preLoaderRoute: typeof ChronicleCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DocsRoute: DocsRoute,
  ItemsRoute: ItemsRoute,
  LoginRoute: LoginRoute,
  NpcsRoute: NpcsRoute,
  OracleRoute: OracleRoute,
  PartyRoute: PartyRoute,
  QuestsRoute: QuestsRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  UsageRoute: UsageRoute,
  ChronicleCampaignIdRoute: ChronicleCampaignIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
